all:
  children:
    new_branch:
      hosts:
        branch-router1:
          device_type: router
          mgmt_ip: 172.199.0.50
          wan_ip: 10.0.2.2
          ospf_area: 0.0.0.0
          ansible_host: 127.0.0.1
          ansible_port: 2301
        branch-switch1:
          device_type: switch
          mgmt_ip: 172.199.0.60
          ansible_host: 127.0.0.1
          ansible_port: 2321
          vlans:
            - { id: 10, name: "Management" }
            - { id: 20, name: "Data" }
  vars:
    provisioner:
      port: 8080
